
services:
  web:
    build: .
    container_name: damn-vulnerable-passkey
    ports:
      - "5000:5000"
    # Load environment variables from the .env file
    env_file:
      - .env
    environment:
      TZ: ${TZ:-Asia/Bangkok}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - webnet
    # Optionally, enforce security options:
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    # Add a restart policy to automatically restart the container
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
